// Copyright (c) 2020 Rumen G.Bogdanovski
// All rights reserved.
//
// You can use this software under the terms of 'INDIGO Astronomy
// open-source license' (see LICENSE.md).
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHORS 'AS IS' AND ANY EXPRESS
// OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
// WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
// ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
// DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
// DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
// GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
// INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
// WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
// NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
// SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#ifndef _IMAGE_PREVIEW_LUT_H
#define _IMAGE_PREVIEW_LUT_H

typedef enum {
	PREVIEW_STRETCH_NONE = 0,
	PREVIEW_STRETCH_SLIGHT,
	PREVIEW_STRETCH_MODERATE,
	PREVIEW_STRETCH_NORMAL,
	PREVIEW_STRETCH_HARD,
	PREVIEW_STRETCH_COUNT
} preview_stretch_level;

typedef enum {
	BLACK = 0,
	WHITE
} preview_stretch_bw;

const float preview_stretch_lut[][2] = {
	{0.05, 0.00},
	{0.05, 0.07},
	{0.05, 0.25},
	{0.05, 0.75},
	{0.05, 1.30}
};

#endif /* _IMAGE_PREVIEW_LUT_H */
